# Generated by Django 4.1.5 on 2023-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='user_token',
            field=models.CharField(max_length=200, null=True, verbose_name='UserToken'),
        ),
    ]
