# Generated by Django 4.1.5 on 2023-01-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_receiver_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token'),
        ),
    ]
